// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.DB.Contexts;

#nullable disable

namespace Warehouse.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.DB.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Computer Keyboard"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Computer Mouse"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Computer Motherboard"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Computer Ram"
                        });
                });

            modelBuilder.Entity("Warehouse.DB.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Description = "Logitech MK235 Wireless Keyboard and Mouse Combo for Windows, 2.4 GHz Wireless with Unifying USB-Receiver, Wireless Mouse, 15 FN Keys, 3-Year",
                            Name = "MK235 Wireless Keyboard",
                            Price = 275m,
                            Quantity = 50
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Description = "SteelSeries Apex Pro TKL HyperMagnetic Gaming Keyboard - World's Fastest Keyboard - Adjustable Actuation - Esports TKL - OLED Screen - PBT Keycaps",
                            Name = "SteelSeries Gaming Keyboard",
                            Price = 820m,
                            Quantity = 20
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 2,
                            Description = "Logitech G305 Lightspeed Wireless Gaming Mouse, HERO Sensor, 12,000 DPI, Lightweight, 6 Programmable Buttons, 250h Battery Life, On-Board Memory,",
                            Name = "Logitech G305 Wireless Mouse",
                            Price = 248m,
                            Quantity = 25
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 3,
                            Description = "MSI PRO B650-S WiFi ProSeries Motherboard (Supports AMD Ryzen 7000 Series Processors, AM5, DDR5, PCIe 4.0, M.2 Slots, SATA 6Gb/s, USB 3.2 Gen 2,",
                            Name = "MSI PRO B650-S WiFi ProSeries Motherboard",
                            Price = 700m,
                            Quantity = 30
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 3,
                            Description = "ASRock B660M Pro RS Intel B660 Series CPU (LGA1700) Compatible B660M MicroATX Motherboard",
                            Name = "ASRock B660M Pro RS Intel",
                            Price = 248m,
                            Quantity = 45
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 3,
                            Description = "Intel Core i7-14700K New Gaming Desktop Processor 20 cores (8 P-cores + 12 E-cores) with Integrated Graphics - Unlocked",
                            Name = "Intel Core i7-14700K Motherboard",
                            Price = 700m,
                            Quantity = 50
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 4,
                            Description = "HPE P00924-B21 memory module 32 GB DDR4 2933 MHz",
                            Name = "HPE DDR4 RAM 32GB",
                            Price = 900m,
                            Quantity = 20
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 4,
                            Description = "CORSAIR VENGEANCE RGB DDR5 RAM 32GB (2x16GB) 6400MHz CL36 Intel XMP iCUE Compatible Computer Memory - Black (CMH32GX5M2B6400C36)",
                            Name = "CORSAIR DDR5 RAM 32GB",
                            Price = 75m,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("Warehouse.DB.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ISActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "admin@gmail.com",
                            FullName = "Test Admin",
                            ISActive = true,
                            Password = "pass1234",
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Warehouse.DB.Entities.Product", b =>
                {
                    b.HasOne("Warehouse.DB.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
